# Use root/root as user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: medick
      POSTGRES_PASSWORD: medick
      POSTGRES_DB: medickDB
    ports:
      - "5432:5432"
