spring:
  application:
    alias: MEDICK
    version: '@project.version@'
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  main:
    banner-mode: OFF
    allow-circular-references: true
  datasource:
    database: medickDB
    db-schema: medickschema
    url: "jdbc:postgresql://localhost:5432/${spring.datasource.database}?currentSchema=${spring.datasource.db-schema}&user=${spring.datasource.username}&password=${spring.datasource.password}"
    username: medick
    password: medick
    hikari:
      pool-name: postgres-local
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        default_schema: ${spring.datasource.db-schema}
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        types.print.banner: false
    hibernate:
      ddl-auto: none
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    schemas: ${spring.datasource.db-schema}
